version: "3.7"
services:
  app:
    restart: always
    ports:
      - 3000:3000
    build: 
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c 'npm run dev'
    volumes:
      - .:/app
